version: "3.8"

networks:
    stamfordcenter:

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.integration.test
        depends_on:
            - db-integration
        networks:
            - stamfordcenter

    db-integration:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: stamfordcenter
        volumes:
            - ./test/data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        networks:
            - stamfordcenter
