name: Pull Request Pipeline

on:
    pull_request:

jobs:
    ci:
        name: Run tests during pull request
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Jest
              run: npm install --save-dev jest ts-jest @types/jest

            - name: Unit test
              run: npm run unit

            - name: Integration test inside Docker Compose
              run: |
                  docker compose -f docker-compose.integration.yml down -v &&
                  docker compose -f docker-compose.integration.yml up --build --force-recreate --abort-on-container-exit --exit-code-from app
